parameters:
  python_version: ''

steps:
- script: |
    # Fix Git SSL errors
    echo "Using pipenv python version: $PIPENV_DEFAULT_PYTHON_VERSION"
    git submodule sync && git submodule update --init --recursive
    pipenv run pytest --junitxml=test-results.xml
  displayName: Run integration tests
  env:
    PY_EXE: $(PY_EXE)
    GIT_SSL_CAINFO: $(GIT_SSL_CAINFO)
    LANG: $(LANG)
    PIP_PROCESS_DEPENDENCY_LINKS: '$(PIP_PROCESS_DEPENDENCY_LINKS)'
    PIPENV_DEFAULT_PYTHON_VERSION: '${{ parameters.python_version }}'
    PYTHONWARNINGS: ignore:DEPRECATION
    PIPENV_NOSPIN: '1'
