engines:
  isort:
    enabled: true
  pep8:
    enabled: true
  pylint:
    enabled: true
    checks:
      import-error:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 100
          python_version: 3
exclude_patterns:
- ".*"
- "**/__pycache__/"
- "tests/"
- "**/test_*"
- "**/patched/"
- "**/vendor/"
ratings:
  paths:
  - pipenv/**
