sudo: false

language: python

cache: pip

python:
  - "2.7"

install:
  - pip install pip==18.0
  - pip install -e .
  - export PIPENV_IGNORE_VIRTUALENVS=1 && pipenv install --dev

script: pipenv run pytest
