name: Pipenv Build Rules
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - docs/*
    - news/*
    - README.md
    - pipenv/*.txt
    - CHANGELOG.rst
    - CONTRIBUTING.md
    - CODE_OF_CONDUCT.md
    - .gitignore
    - .gitattributes
    - .editorconfig

phases:
- template: phases/test.yml
  parameters:
    queue: Hosted VS2017
